#!/usr/bin/env bash
# =============================================================================
#  Natasun Chat — Interactive Installer/Updater
#  ============================================================================
#  Run:  curl -sSL <url> | bash        (one-command install)
#  Or:   bash install.sh                (from a cloned repo)
#
#  It asks a few questions, sets up everything (domain + free SSL via Caddy,
#  database, .env, admin account), builds, and starts the service.
# =============================================================================
set -e

YELLOW='\033[1;33m'; GREEN='\033[1;32m'; CYAN='\033[1;36m'; RED='\033[1;31m'; NC='\033[0m'
say()  { echo -e "${GREEN}[natasun]${NC} $*"; }
info() { echo -e "${CYAN}  >${NC} $*"; }
warn() { echo -e "${YELLOW}  !${NC} $*"; }
die()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ---- Resolve where this script lives (works for curl|bash and clones) ----
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
APP_DIR="${APP_DIR:-$SCRIPT_DIR}"
REPO_URL="${REPO_URL:-https://github.com/vahidtakro/natasun-chat}"

# ------------------------------------------------------------------ helpers
read_input() {  # $1 prompt, $2 default
  local prompt="$1" default="$2" val
  if [ -n "$default" ]; then
    read -r -p "$(echo -e "${CYAN}  >${NC} $prompt [${default}]: ")" val
  else
    read -r -p "$(echo -e "${CYAN}  >${NC} $prompt: ")" val
  fi
  echo "${val:-$default}"
}

generate_secret() { head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c 48; }

create_env() {
  say "Writing .env..."
  cat > "$APP_DIR/.env" <<EOF
# === Natasun Chat environment (auto-generated by install.sh) ===
DATABASE_URL="mysql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

# Public URLs (used by the widget and dashboard)
NEXT_PUBLIC_APP_URL="${APP_URL}"
NEXT_PUBLIC_WS_URL="${WS_URL}"
WS_PORT=3001

# Auth secrets (auto-generated)
SESSION_SECRET="${SESSION_SECRET}"
JWT_SECRET="${JWT_SECRET}"

# WebSocket CORS: allow the dashboard host + optional extra origins
ALLOWED_ORIGINS="${ALLOWED_ORIGINS}"

# App branding defaults (admin is asked during onboarding in the UI)
DEFAULT_BRAND_COLOR="${BRAND_COLOR}"
DEFAULT_BRAND_NAME="${BRAND_NAME}"

# --- Docker Compose variables (used by the optional bundled MySQL) ---
DB_NAME="${DB_NAME}"
DB_USER="${DB_USER}"
DB_PASS="${DB_PASS}"
DB_ROOT_PASS="${DB_ROOT_PASS:-change-me-change-me}"
EOF
  chmod 600 "$APP_DIR/.env"
  info ".env created."
}

create_caddyfile() {
  # If a domain is set -> HTTPS certificate domain. Otherwise plain HTTP.
  if [ -n "$APP_DOMAIN" ]; then
    cat > "$APP_DIR/Caddyfile" <<EOF
$APP_DOMAIN {
	@ws {
		path /socket.io/*
	}
	reverse_proxy @ws app:3001
	reverse_proxy app:3000
	encode gzip
	header {
		Strict-Transport-Security "max-age=31536000"
		X-Content-Type-Options nosniff
	}
}
EOF
  else
    cat > "$APP_DIR/Caddyfile" <<'EOF'
:80 {
	@ws {
		path /socket.io/*
	}
	reverse_proxy @ws app:3001
	reverse_proxy app:3000
	encode gzip
	header {
		X-Content-Type-Options nosniff
	}
}
EOF
  fi
  info "Caddyfile configured."
}

# ------------------------------------------------------------------ main
echo ""
echo "============================================================"
echo "  Natasun Chat — Setup Wizard"
echo "============================================================"
echo ""

# ---- 0. Clone if we were run via curl (no local repo yet) ----
if [ ! -f "$APP_DIR/package.json" ]; then
  if ! command -v git >/dev/null 2>&1; then die "git is not installed."; fi
  if [ -z "$(ls -A "$APP_DIR" 2>/dev/null)" ]; then
    say "Downloading Natasun Chat..."
    git clone --depth 1 "$REPO_URL" "$APP_DIR" || die "Clone failed."
  else
    say "Downloading Natasun Chat into subfolder..."
    git clone --depth 1 "$REPO_URL" "$APP_DIR/natasun-chat" || die "Clone failed."
    APP_DIR="$APP_DIR/natasun-chat"
  fi
  cd "$APP_DIR"
fi
cd "$APP_DIR"

# ---- 1. Welcome / collect answers ----
info "Let's get you set up. You can press Enter to accept defaults."
echo ""

BRAND_NAME=$(read_input "What is your company / website name?" "My Website")
BRAND_COLOR=$(read_input "Widget brand color (hex)?" "#00A76F")
APP_DOMAIN=$(read_input "Domain for this chat (e.g. chat.mysite.com). Leave BLANK to use your server's IP" "")

if [ -n "$APP_DOMAIN" ]; then
  # Normalize: strip http(s):// and trailing slash
  APP_DOMAIN="${APP_DOMAIN#https://}"; APP_DOMAIN="${APP_DOMAIN#http://}"; APP_DOMAIN="${APP_DOMAIN%/}"
  PROTOCOL="https"
  APP_URL="https://$APP_DOMAIN"
  WS_URL="${APP_URL}/socket.io"   # WebSocket proxied by Caddy (wss)
else
  # IP access: Caddy serves HTTP on port 80; WS is proxied at the same origin.
  SERVER_IP=$(curl -s https://api.ipify.org || echo "")
  PROTOCOL="http"
  if [ -n "$SERVER_IP" ]; then
    APP_URL="http://$SERVER_IP"
    WS_URL="${APP_URL}/socket.io"
    info "Your server public IP appears to be: $SERVER_IP"
  else
    APP_URL="http://YOUR_SERVER_IP"
    WS_URL="${APP_URL}/socket.io"
    warn "Could not detect your IP automatically. Edit .env later if needed."
  fi
fi

# WebSocket CORS: the browser widget connects from many different websites,
# so we allow any origin (the handshake itself is handled via channel auth).
ALLOWED_ORIGINS="*"
echo ""

# ---- 2. Database ----
echo "------------------------------------------------------------"
info "DATABASE (MySQL)"
echo "------------------------------------------------------------"
USE_EXT=$(read_input "Use an existing MySQL (recommended) or bundle one with Docker? [external/bundle]" "external")
if [ "$USE_EXT" = "bundle" ]; then
  DB_HOST="db"; DB_PORT="3306"; DB_NAME="natasun_chat"
  DB_USER="natasun"; DB_PASS=$(generate_secret)
  DB_ROOT_PASS=$(generate_secret)
else
  DB_HOST=$(read_input "MySQL host?" "127.0.0.1")
  DB_PORT=$(read_input "MySQL port?" "3306")
  DB_NAME=$(read_input "Database name?" "natasun_chat")
  DB_USER=$(read_input "Database username?" "root")
  echo ""
  warn "Enter database password (won't be displayed):"
  read -rs DB_PASS; echo ""
  [ -n "$DB_PASS" ] || die "Database password cannot be empty."
fi
echo ""

# ---- 3. Auth secrets ----
SESSION_SECRET=$(generate_secret)
JWT_SECRET=$(generate_secret)

# ---- 4. Generate files ----
create_env
create_caddyfile

# Skip Caddy in IP mode? No — keep Caddy so config is uniform.
# In IP mode Caddy serves plain HTTP on :80.

# ---- 5. Wait for MySQL to be ready if bundled ----
COMPOSE_PROFILE=""
if [ "$USE_EXT" = "bundle" ]; then
  COMPOSE_PROFILE="--profile db"
  say "Starting database first (waiting for it to be ready)..."
  docker compose --profile db up -d db 2>/dev/null || true
  sleep 15
fi

# ---- 6. Build & start ----
say "Building containers (first run takes a few minutes)..."
docker compose $COMPOSE_PROFILE up -d --build

say "Waiting for services to be ready..."
sleep 8

say "Done! Checking status..."
docker compose ps

echo ""
echo "============================================================"
echo "  ✅ Natasun Chat is now running!"
echo "============================================================"
echo ""
echo "  Dashboard:  $APP_URL"
echo ""
echo "  Note: The first time you open it, click \"Create an account\""
echo "        to set up your admin login (first admin = workspace owner)."
echo ""
if [ -n "$APP_DOMAIN" ]; then
  echo "  SSL is enabled automatically (free Let's Encrypt cert via Caddy)."
fi
echo ""
warn "Keep the file $APP_DIR/.env safe (contains your secrets and DB password)."
echo ""
